package com.android.location.dao;

import com.android.location.pojo.TbGroupmember;
import java.util.List;

public interface TbGroupmemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_groupmember
     *
     * @mbg.generated
     */
    int insert(TbGroupmember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_groupmember
     *
     * @mbg.generated
     */
    List<TbGroupmember> selectAll();
}