package com.android.location.dao;

import com.android.location.pojo.TbGroup;
import java.util.List;

public interface TbGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbg.generated
     */
    int insert(TbGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbg.generated
     */
    List<TbGroup> selectAll();
}