package com.android.location.dao;

import com.android.location.pojo.TbOriginatorSign;
import java.util.List;

public interface TbOriginatorSignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_originator_sign
     *
     * @mbg.generated
     */
    int insert(TbOriginatorSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_originator_sign
     *
     * @mbg.generated
     */
    List<TbOriginatorSign> selectAll();
}