package com.android.location.dao;

import com.android.location.pojo.TbReceiverSign;
import java.util.List;

public interface TbReceiverSignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_receiver_sign
     *
     * @mbg.generated
     */
    int insert(TbReceiverSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_receiver_sign
     *
     * @mbg.generated
     */
    List<TbReceiverSign> selectAll();
}