package com.android.location.dao;

import com.android.location.pojo.TbTsmessage;
import java.util.List;

public interface TbTsmessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tsmessage
     *
     * @mbg.generated
     */
    int insert(TbTsmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tsmessage
     *
     * @mbg.generated
     */
    List<TbTsmessage> selectAll();
}