package com.android.location.dao;

import com.android.location.pojo.TbUserinfo;
import java.util.List;

public interface TbUserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated
     */
    int insert(TbUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated
     */
    List<TbUserinfo> selectAll();
}