package com.android.location.dao;

import com.android.location.pojo.TbUserinfo;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TbUserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated
     */
    int insert(TbUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated
     */
    List<TbUserinfo> selectAll();
    
    /**
     * 通过用户名和密码查询用户
     * @param username
     * @param password
     * @return
     */
    TbUserinfo selecTbUserInfo(@Param("username")String username, @Param("password")String password);
    
    TbUserinfo selecTbUserInfoByToken(String token);
    
    int updateUserInfo(TbUserinfo tbUserinfo);
    
    
}