package com.android.location.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.groupname
     *
     * @mbg.generated
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.group_owner_token
     *
     * @mbg.generated
     */
    private String groupOwnerToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.group_introduce
     *
     * @mbg.generated
     */
    private String groupIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.group_create_time
     *
     * @mbg.generated
     */
    private Date groupCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_group
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.group_id
     *
     * @return the value of tb_group.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.group_id
     *
     * @param groupId the value for tb_group.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.groupname
     *
     * @return the value of tb_group.groupname
     *
     * @mbg.generated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.groupname
     *
     * @param groupname the value for tb_group.groupname
     *
     * @mbg.generated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.group_owner_token
     *
     * @return the value of tb_group.group_owner_token
     *
     * @mbg.generated
     */
    public String getGroupOwnerToken() {
        return groupOwnerToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.group_owner_token
     *
     * @param groupOwnerToken the value for tb_group.group_owner_token
     *
     * @mbg.generated
     */
    public void setGroupOwnerToken(String groupOwnerToken) {
        this.groupOwnerToken = groupOwnerToken == null ? null : groupOwnerToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.group_introduce
     *
     * @return the value of tb_group.group_introduce
     *
     * @mbg.generated
     */
    public String getGroupIntroduce() {
        return groupIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.group_introduce
     *
     * @param groupIntroduce the value for tb_group.group_introduce
     *
     * @mbg.generated
     */
    public void setGroupIntroduce(String groupIntroduce) {
        this.groupIntroduce = groupIntroduce == null ? null : groupIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.group_create_time
     *
     * @return the value of tb_group.group_create_time
     *
     * @mbg.generated
     */
    public Date getGroupCreateTime() {
        return groupCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.group_create_time
     *
     * @param groupCreateTime the value for tb_group.group_create_time
     *
     * @mbg.generated
     */
    public void setGroupCreateTime(Date groupCreateTime) {
        this.groupCreateTime = groupCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupId=").append(groupId);
        sb.append(", groupname=").append(groupname);
        sb.append(", groupOwnerToken=").append(groupOwnerToken);
        sb.append(", groupIntroduce=").append(groupIntroduce);
        sb.append(", groupCreateTime=").append(groupCreateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}