package com.android.location.pojo;

import java.io.Serializable;

public class TbGroupmember implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_groupmember. group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_groupmember.member_token
     *
     * @mbg.generated
     */
    private String memberToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_groupmember.is_check
     *
     * @mbg.generated
     */
    private Boolean isCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_groupmember
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_groupmember. group_id
     *
     * @return the value of tb_groupmember. group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_groupmember. group_id
     *
     * @param groupId the value for tb_groupmember. group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_groupmember.member_token
     *
     * @return the value of tb_groupmember.member_token
     *
     * @mbg.generated
     */
    public String getMemberToken() {
        return memberToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_groupmember.member_token
     *
     * @param memberToken the value for tb_groupmember.member_token
     *
     * @mbg.generated
     */
    public void setMemberToken(String memberToken) {
        this.memberToken = memberToken == null ? null : memberToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_groupmember.is_check
     *
     * @return the value of tb_groupmember.is_check
     *
     * @mbg.generated
     */
    public Boolean getIsCheck() {
        return isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_groupmember.is_check
     *
     * @param isCheck the value for tb_groupmember.is_check
     *
     * @mbg.generated
     */
    public void setIsCheck(Boolean isCheck) {
        this.isCheck = isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_groupmember
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupId=").append(groupId);
        sb.append(", memberToken=").append(memberToken);
        sb.append(", isCheck=").append(isCheck);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}