package com.android.location.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbOriginatorSign implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_originator_sign.originator_sign_id
     *
     * @mbg.generated
     */
    private Integer originatorSignId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_originator_sign.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_originator_sign.originator_token
     *
     * @mbg.generated
     */
    private String originatorToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_originator_sign.send_time
     *
     * @mbg.generated
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_originator_sign.longitude
     *
     * @mbg.generated
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_originator_sign.latitude
     *
     * @mbg.generated
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_originator_sign.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_originator_sign
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_originator_sign.originator_sign_id
     *
     * @return the value of tb_originator_sign.originator_sign_id
     *
     * @mbg.generated
     */
    public Integer getOriginatorSignId() {
        return originatorSignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_originator_sign.originator_sign_id
     *
     * @param originatorSignId the value for tb_originator_sign.originator_sign_id
     *
     * @mbg.generated
     */
    public void setOriginatorSignId(Integer originatorSignId) {
        this.originatorSignId = originatorSignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_originator_sign.group_id
     *
     * @return the value of tb_originator_sign.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_originator_sign.group_id
     *
     * @param groupId the value for tb_originator_sign.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_originator_sign.originator_token
     *
     * @return the value of tb_originator_sign.originator_token
     *
     * @mbg.generated
     */
    public String getOriginatorToken() {
        return originatorToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_originator_sign.originator_token
     *
     * @param originatorToken the value for tb_originator_sign.originator_token
     *
     * @mbg.generated
     */
    public void setOriginatorToken(String originatorToken) {
        this.originatorToken = originatorToken == null ? null : originatorToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_originator_sign.send_time
     *
     * @return the value of tb_originator_sign.send_time
     *
     * @mbg.generated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_originator_sign.send_time
     *
     * @param sendTime the value for tb_originator_sign.send_time
     *
     * @mbg.generated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_originator_sign.longitude
     *
     * @return the value of tb_originator_sign.longitude
     *
     * @mbg.generated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_originator_sign.longitude
     *
     * @param longitude the value for tb_originator_sign.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_originator_sign.latitude
     *
     * @return the value of tb_originator_sign.latitude
     *
     * @mbg.generated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_originator_sign.latitude
     *
     * @param latitude the value for tb_originator_sign.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_originator_sign.region
     *
     * @return the value of tb_originator_sign.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_originator_sign.region
     *
     * @param region the value for tb_originator_sign.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_originator_sign
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", originatorSignId=").append(originatorSignId);
        sb.append(", groupId=").append(groupId);
        sb.append(", originatorToken=").append(originatorToken);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", region=").append(region);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}