package com.android.location.pojo;

import java.io.Serializable;

public class TbReceiverSign implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_sign.receiver_id
     *
     * @mbg.generated
     */
    private Integer receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_sign.receiver_token
     *
     * @mbg.generated
     */
    private String receiverToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_sign.rlatitude
     *
     * @mbg.generated
     */
    private String rlatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_sign.state
     *
     * @mbg.generated
     */
    private Boolean state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_sign.done
     *
     * @mbg.generated
     */
    private Boolean done;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_sign.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receiver_sign.sign_id
     *
     * @mbg.generated
     */
    private Integer signId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_receiver_sign
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_sign.receiver_id
     *
     * @return the value of tb_receiver_sign.receiver_id
     *
     * @mbg.generated
     */
    public Integer getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_sign.receiver_id
     *
     * @param receiverId the value for tb_receiver_sign.receiver_id
     *
     * @mbg.generated
     */
    public void setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_sign.receiver_token
     *
     * @return the value of tb_receiver_sign.receiver_token
     *
     * @mbg.generated
     */
    public String getReceiverToken() {
        return receiverToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_sign.receiver_token
     *
     * @param receiverToken the value for tb_receiver_sign.receiver_token
     *
     * @mbg.generated
     */
    public void setReceiverToken(String receiverToken) {
        this.receiverToken = receiverToken == null ? null : receiverToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_sign.rlatitude
     *
     * @return the value of tb_receiver_sign.rlatitude
     *
     * @mbg.generated
     */
    public String getRlatitude() {
        return rlatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_sign.rlatitude
     *
     * @param rlatitude the value for tb_receiver_sign.rlatitude
     *
     * @mbg.generated
     */
    public void setRlatitude(String rlatitude) {
        this.rlatitude = rlatitude == null ? null : rlatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_sign.state
     *
     * @return the value of tb_receiver_sign.state
     *
     * @mbg.generated
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_sign.state
     *
     * @param state the value for tb_receiver_sign.state
     *
     * @mbg.generated
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_sign.done
     *
     * @return the value of tb_receiver_sign.done
     *
     * @mbg.generated
     */
    public Boolean getDone() {
        return done;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_sign.done
     *
     * @param done the value for tb_receiver_sign.done
     *
     * @mbg.generated
     */
    public void setDone(Boolean done) {
        this.done = done;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_sign.result
     *
     * @return the value of tb_receiver_sign.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_sign.result
     *
     * @param result the value for tb_receiver_sign.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receiver_sign.sign_id
     *
     * @return the value of tb_receiver_sign.sign_id
     *
     * @mbg.generated
     */
    public Integer getSignId() {
        return signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receiver_sign.sign_id
     *
     * @param signId the value for tb_receiver_sign.sign_id
     *
     * @mbg.generated
     */
    public void setSignId(Integer signId) {
        this.signId = signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_receiver_sign
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", receiverId=").append(receiverId);
        sb.append(", receiverToken=").append(receiverToken);
        sb.append(", rlatitude=").append(rlatitude);
        sb.append(", state=").append(state);
        sb.append(", done=").append(done);
        sb.append(", result=").append(result);
        sb.append(", signId=").append(signId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}