package com.android.location.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbTsmessage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tsmessage.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tsmessage.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tsmessage.receiver
     *
     * @mbg.generated
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tsmessage.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tsmessage.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tsmessage.sendperson_id
     *
     * @mbg.generated
     */
    private Integer sendpersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tsmessage.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tsmessage.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_tsmessage
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tsmessage.id
     *
     * @return the value of tb_tsmessage.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tsmessage.id
     *
     * @param id the value for tb_tsmessage.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tsmessage.type
     *
     * @return the value of tb_tsmessage.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tsmessage.type
     *
     * @param type the value for tb_tsmessage.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tsmessage.receiver
     *
     * @return the value of tb_tsmessage.receiver
     *
     * @mbg.generated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tsmessage.receiver
     *
     * @param receiver the value for tb_tsmessage.receiver
     *
     * @mbg.generated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tsmessage.content
     *
     * @return the value of tb_tsmessage.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tsmessage.content
     *
     * @param content the value for tb_tsmessage.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tsmessage.state
     *
     * @return the value of tb_tsmessage.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tsmessage.state
     *
     * @param state the value for tb_tsmessage.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tsmessage.sendperson_id
     *
     * @return the value of tb_tsmessage.sendperson_id
     *
     * @mbg.generated
     */
    public Integer getSendpersonId() {
        return sendpersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tsmessage.sendperson_id
     *
     * @param sendpersonId the value for tb_tsmessage.sendperson_id
     *
     * @mbg.generated
     */
    public void setSendpersonId(Integer sendpersonId) {
        this.sendpersonId = sendpersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tsmessage.group_id
     *
     * @return the value of tb_tsmessage.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tsmessage.group_id
     *
     * @param groupId the value for tb_tsmessage.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tsmessage.create_time
     *
     * @return the value of tb_tsmessage.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tsmessage.create_time
     *
     * @param createTime the value for tb_tsmessage.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tsmessage
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", receiver=").append(receiver);
        sb.append(", content=").append(content);
        sb.append(", state=").append(state);
        sb.append(", sendpersonId=").append(sendpersonId);
        sb.append(", groupId=").append(groupId);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}