package com.android.location.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbUserinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.realName
     *
     * @mbg.generated
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.head_photo_addr
     *
     * @mbg.generated
     */
    private String headPhotoAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.isTeacher
     *
     * @mbg.generated
     */
    private Boolean isteacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.phone_number
     *
     * @mbg.generated
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_userinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.user_id
     *
     * @return the value of tb_userinfo.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.user_id
     *
     * @param userId the value for tb_userinfo.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.token
     *
     * @return the value of tb_userinfo.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.token
     *
     * @param token the value for tb_userinfo.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.username
     *
     * @return the value of tb_userinfo.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.username
     *
     * @param username the value for tb_userinfo.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.password
     *
     * @return the value of tb_userinfo.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.password
     *
     * @param password the value for tb_userinfo.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.realName
     *
     * @return the value of tb_userinfo.realName
     *
     * @mbg.generated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.realName
     *
     * @param realname the value for tb_userinfo.realName
     *
     * @mbg.generated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.head_photo_addr
     *
     * @return the value of tb_userinfo.head_photo_addr
     *
     * @mbg.generated
     */
    public String getHeadPhotoAddr() {
        return headPhotoAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.head_photo_addr
     *
     * @param headPhotoAddr the value for tb_userinfo.head_photo_addr
     *
     * @mbg.generated
     */
    public void setHeadPhotoAddr(String headPhotoAddr) {
        this.headPhotoAddr = headPhotoAddr == null ? null : headPhotoAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.isTeacher
     *
     * @return the value of tb_userinfo.isTeacher
     *
     * @mbg.generated
     */
    public Boolean getIsteacher() {
        return isteacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.isTeacher
     *
     * @param isteacher the value for tb_userinfo.isTeacher
     *
     * @mbg.generated
     */
    public void setIsteacher(Boolean isteacher) {
        this.isteacher = isteacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.phone_number
     *
     * @return the value of tb_userinfo.phone_number
     *
     * @mbg.generated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.phone_number
     *
     * @param phoneNumber the value for tb_userinfo.phone_number
     *
     * @mbg.generated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.createTime
     *
     * @return the value of tb_userinfo.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.createTime
     *
     * @param createtime the value for tb_userinfo.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", token=").append(token);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", realname=").append(realname);
        sb.append(", headPhotoAddr=").append(headPhotoAddr);
        sb.append(", isteacher=").append(isteacher);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}